export const border = {
  "blue-gray": "border-blue-gray-500",
  gray: "border-gray-500",
  brown: "border-brown-500",
  "deep-orange": "border-deep-orange-500",
  orange: "border-orange-500",
  amber: "border-amber-500",
  yellow: "border-yellow-500",
  lime: "border-lime-500",
  "light-green": "border-light-green-500",
  green: "border-green-500",
  teal: "border-teal-500",
  cyan: "border-cyan-500",
  "light-blue": "border-light-blue-500",
  blue: "border-blue-500",
  indigo: "border-indigo-500",
  "deep-purple": "border-deep-purple-500",
  purple: "border-purple-500",
  pink: "border-pink-500",
  red: "border-red-500",
};
