export const variantStyle = {
  filled: {
    "blue-gray": "bg-blue-gray-500",
    gray: "bg-gray-500",
    brown: "bg-brown-500",
    "deep-orange": "bg-deep-orange-500",
    orange: "bg-orange-500",
    amber: "bg-amber-500",
    yellow: "bg-yellow-500",
    lime: "bg-lime-500",
    "light-green": "bg-light-green-500",
    green: "bg-green-500",
    teal: "bg-teal-500",
    cyan: "bg-cyan-500",
    "light-blue": "bg-light-blue-500",
    blue: "bg-blue-500",
    indigo: "bg-indigo-500",
    "deep-purple": "bg-deep-purple-500",
    purple: "bg-purple-500",
    pink: "bg-pink-500",
    red: "bg-red-500",
    transparent: "bg-transparent",
    white: "bg-white",
    black: "bg-black",
  },
  gradient: {
    "blue-gray": "bg-gradient-to-tr from-blue-gray-600 to-blue-gray-400",
    gray: "bg-gradient-to-tr from-gray-600 to-gray-400",
    brown: "bg-gradient-to-tr from-brown-600 to-brown-400",
    "deep-orange": "bg-gradient-to-tr from-deep-orange-600 to-deep-orange-400",
    orange: "bg-gradient-to-tr from-orange-600 to-orange-400",
    amber: "bg-gradient-to-tr from-amber-600 to-amber-400",
    yellow: "bg-gradient-to-tr from-yellow-600 to-yellow-400",
    lime: "bg-gradient-to-tr from-lime-600 to-lime-400",
    "light-green": "bg-gradient-to-tr from-light-green-600 to-light-green-400",
    green: "bg-gradient-to-tr from-green-600 to-green-400",
    teal: "bg-gradient-to-tr from-teal-600 to-teal-400",
    cyan: "bg-gradient-to-tr from-cyan-600 to-cyan-400",
    "light-blue": "bg-gradient-to-tr from-light-blue-600 to-light-blue-400",
    blue: "bg-gradient-to-tr from-blue-600 to-blue-400",
    indigo: "bg-gradient-to-tr from-indigo-600 to-indigo-400",
    "deep-purple": "bg-gradient-to-tr from-deep-purple-600 to-deep-purple-400",
    purple: "bg-gradient-to-tr from-purple-600 to-purple-400",
    pink: "bg-gradient-to-tr from-pink-600 to-pink-400",
    red: "bg-gradient-to-tr from-red-600 to-red-400",
  },
  others: {
    800: {
      "blue-gray": "bg-blue-gray-800",
      gray: "bg-gray-800",
      brown: "bg-brown-800",
      "deep-orange": "bg-deep-orange-800",
      orange: "bg-orange-800",
      amber: "bg-amber-800",
      yellow: "bg-yellow-800",
      lime: "bg-lime-800",
      "light-green": "bg-light-green-800",
      green: "bg-green-800",
      teal: "bg-teal-800",
      cyan: "bg-cyan-800",
      "light-blue": "bg-light-blue-800",
      blue: "bg-blue-800",
      indigo: "bg-indigo-800",
      "deep-purple": "bg-deep-purple-800",
      purple: "bg-purple-800",
      pink: "bg-pink-800",
      red: "bg-red-800",
    },
  },
};
