export const ring = {
  "blue-gray": "ring-blue-gray-200",
  gray: "ring-gray-200",
  brown: "ring-brown-200",
  "deep-orange": "ring-deep-orange-200",
  orange: "ring-orange-200",
  amber: "ring-amber-200",
  yellow: "ring-yellow-200",
  lime: "ring-lime-200",
  "light-green": "ring-light-green-200",
  green: "ring-green-200",
  teal: "ring-teal-200",
  cyan: "ring-cyan-200",
  "light-blue": "ring-light-blue-200",
  blue: "ring-blue-200",
  indigo: "ring-indigo-200",
  "deep-purple": "ring-deep-purple-200",
  purple: "ring-purple-200",
  pink: "ring-pink-200",
  red: "ring-red-200",
};
