export const text = {
  "blue-gray": "text-blue-gray-500",
  gray: "text-gray-500",
  brown: "text-brown-500",
  "deep-orange": "text-deep-orange-500",
  orange: "text-orange-500",
  amber: "text-amber-500",
  yellow: "text-yellow-500",
  lime: "text-lime-500",
  "light-green": "text-light-green-500",
  green: "text-green-500",
  teal: "text-teal-500",
  cyan: "text-cyan-500",
  "light-blue": "text-light-blue-500",
  blue: "text-blue-500",
  indigo: "text-indigo-500",
  "deep-purple": "text-deep-purple-500",
  purple: "text-purple-500",
  pink: "text-pink-500",
  red: "text-red-500",
  white: "text-white",
  black: "text-black",
  current: "currentColor",
  inherit: "inherit",
};
